
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class QuizNumber extends javax.swing.JFrame {

    /**
     * Creates new form QuizNumber
     */
    public QuizNumber() {
        initComponents();
    }
  
    public static String quizName="";
    public static String tableName="";
    public static String currentTable="";
DefaultListModel mod =new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        proceed = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Choose Quiz");

        jScrollPane1.setViewportView(list);

        proceed.setText("Proceed");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        add.setText("Add Quiz");
        add.setEnabled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        delete.setText("Delete Quiz");
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(proceed)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceed)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(delete))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
String newQuiz =JOptionPane.showInputDialog("Enter quiz name");
list.setModel(mod);
if(newQuiz.equals(""))
    JOptionPane.showMessageDialog(null, "Enter a quiz name first");
else if(mod.contains(newQuiz))
    JOptionPane.showMessageDialog(null, "Quiz with this name already exists");
else
{
    Connection connection =null;
    Subjects subject=new Subjects();
    try{
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/softablitz";
        connection = DriverManager.getConnection(url, "root", "");
        String query1 ="INSERT INTO subjects VALUES (?,?);";
        PreparedStatement preStat = connection.prepareStatement(query1);
        preStat.setString(1, subject.subjectName);
        preStat.setString(2, newQuiz);
        preStat.executeUpdate();
        mod.addElement(newQuiz);
         
        tableName= Subjects.subjectName+"_" + newQuiz;//for having specific table name
        String query2 = "Create table "+   tableName
            + " (id int primary key auto_increment,"    
            + " question varchar(250) ,"
            + " option1 varchar(150),"
            + " option2 varchar(150), "
            + " option3 varchar(150),"
            + " option4 varchar(150),"
            + " answer varchar(150));";
        PreparedStatement psmt = connection.prepareStatement(query2);
        psmt.executeUpdate();    
  }
  catch(Exception e){
    System.out.println("Exeution failed at line :-" + e);
     e.printStackTrace();
    }
  finally{
        try{connection.close();} catch(Exception e) {}            
    }

}    
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
if(list.getSelectedIndex()>=0)
{
    quizName=list.getSelectedValue().toString();
    Subjects subject=new Subjects();
    currentTable= subject.subjectName+"_"+ list.getSelectedValue();
    Connection connection=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/softablitz";
        connection = DriverManager.getConnection(url, "root", "");
        String query="Select count(id) from " + currentTable + ";";
        PreparedStatement preStat = connection.prepareStatement(query);
        ResultSet result = preStat.executeQuery();
        result.next();
        int question_count=result.getInt("count(id)");
        if(question_count==0)
            JOptionPane.showMessageDialog(null,"This quiz has no questions..!");
        else if(new Signup().accessor.equals("teacher")) 
        { 
            new Question().setVisible(true);
            dispose();
        }
        else
        {
            query="Select count(*),marks from marks where registration_no=? and quiz=?;";
            preStat = connection.prepareStatement(query);
            preStat.setInt(1, Login.regNo);
            preStat.setString(2,currentTable);
            result = preStat.executeQuery();
            result.next();
            if(result.getInt("count(*)")==1)
                JOptionPane.showMessageDialog(null, "You have already given the test."+
                        "\n Your score :-" +result.getInt("marks") );
            else
            {
                Test test=new Test();
                test.display_first();
                test.setVisible(true);
                dispose();
            }
        }
    }

    catch(Exception e )
    {
        System.out.println("Exeution failed at line :-" + e);
    }
    finally{
        try{connection.close();} catch(Exception e){}
    }
        
       
}          
// TODO add your handling code here:
    }//GEN-LAST:event_proceedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Subjects subject =new Subjects();
if(Signup.accessor.equals("teacher"))
{
    subject.changePass.setEnabled(true);
    subject.addSubject.setEnabled(true);
    subject.access=1;
}
subject.setVisible(true);
subject.display();
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
if(list.getSelectedIndex()>=0)
{
    String quiz=list.getSelectedValue().toString();
    tableName= Subjects.subjectName+"_" + quiz;
    Connection connection=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/softablitz";
        connection = DriverManager.getConnection(url, "root", "");
        String query1 = "Drop table "+tableName+" ;";
        PreparedStatement preStat = connection.prepareStatement(query1);
        preStat.executeUpdate();
        mod.removeElement(quiz);
        query1 ="Delete from subjects where subject=? and quiz=?;";
        preStat = connection.prepareStatement(query1);
        preStat.setString(1,Subjects.subjectName);
        preStat.setString(2, quiz);
        preStat.executeUpdate();
    }
    catch(Exception e){
        System.out.println("Exeution failed at line :-" + e);
    }
    finally{
        try{connection.close();} catch(Exception e){}
    }
}  
else
    JOptionPane.showMessageDialog(null,"You need to select a quiz to remove it..!") ;
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    
     void display()   //to display quizes already present in database
    {
        Connection connection =null; 
        try{
            list.setModel(mod);
            String quiz="",sbjct=new Subjects().subjectName;
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/softablitz";
            connection = DriverManager.getConnection(url, "root", "");
            String query1 = "Select quiz from subjects where subject=? && quiz is NOT NULL ;";
            PreparedStatement preStat = connection.prepareStatement(query1);
            preStat.setString(1,sbjct);
            ResultSet result = preStat.executeQuery();
            while(result.next()) {
               quiz=result.getString("quiz");
               mod.addElement(quiz);
          }
        
}
    catch(Exception e )
    {
        System.out.println("Exeution failed at line :-" + e);
    }
    finally{
        try{connection.close();} catch(Exception e) {}            
       }    

    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizNumber().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JButton delete;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList list;
    private javax.swing.JButton proceed;
    // End of variables declaration//GEN-END:variables
}
