/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;//for DefaultListModel
/**
 *
 * @author Acer
 */
public class Subjects extends javax.swing.JFrame {

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
    }
    public static  String subjectName="";
DefaultListModel mod =new DefaultListModel();

public int access=0;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        proceed = new javax.swing.JButton();
        addSubject = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        changePass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Choose Subject");

        jScrollPane1.setViewportView(list);

        proceed.setText("Proceed");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        addSubject.setText("Add Subject");
        addSubject.setEnabled(false);
        addSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        changePass.setText("Change Password");
        changePass.setEnabled(false);
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(proceed)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addSubject))))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePass)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proceed)
                            .addComponent(addSubject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePass)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void addSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectActionPerformed
String newSubject="";
try{
    String a=JOptionPane.showInputDialog("Enter subject name");
    if(a != null)
        newSubject =a;
}
catch(Exception e)
{}
list.setModel(mod);
if(newSubject.equals(""))
    JOptionPane.showMessageDialog(null, "Enter a subject first");
else
{
    Connection connection=null;
    PreparedStatement preStat;
    try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/softablitz";
            connection= DriverManager.getConnection(url, "root", "");
            String query="Select distinct(subject) from subjects where subject=?;";
            preStat = connection.prepareStatement(query);
            preStat.setString(1,newSubject);
            ResultSet result=preStat.executeQuery();
            int count=0;
            while(result.next())
            {
                count++;
            }
            if(count==0)
            {
                String query1 ="INSERT INTO subjects VALUES (?,?);";
                preStat = connection.prepareStatement(query1);
                preStat.setString(1, newSubject);
                preStat.setString(2, null);
                preStat.executeUpdate();
                mod.addElement(newSubject);
            }  
            else
                JOptionPane.showMessageDialog(null,"Subject already exists");
      }
      catch(Exception e){
        System.out.println("Exeution failed at line :-" + e);
    }
      finally{
        try{connection.close();} catch(Exception e) {}            
       }

}
        // TODO add your handling code here:
    }//GEN-LAST:event_addSubjectActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        if(list.getSelectedIndex()>=0)
        {
            subjectName=list.getSelectedValue().toString();
            dispose();
            QuizNumber qn= new QuizNumber();
            qn.setVisible(true);
            if(access==1)
            {
                qn.add.setEnabled(true);
                qn.delete.setEnabled(true);
            }
            qn.display();
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_proceedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//new TeacherLogin().setVisible(true);
//dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
    Connection connection = null;
    try{
        String oldPass=JOptionPane.showInputDialog("Enter old Password");
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/softablitz";
        connection = DriverManager.getConnection(url, "root", "");
        String q="Update teacher set password = ? where username='admin' ;";
        String query1 = "Select password from teacher;";
        PreparedStatement psmt = connection.prepareStatement(query1);
        ResultSet result = psmt.executeQuery();
        result.next();
        String old=result.getString("password");
        
        byte[] salt = Signup.getSalt();
        String securePassword = Signup.getSecurePassword(oldPass, salt);
        
        if(old.equals(securePassword))
        {
            String newPass=JOptionPane.showInputDialog("Enter new Password");
            PreparedStatement preStat = connection.prepareStatement(q);
            preStat.setString(1,Signup.getSecurePassword(newPass, salt));
            preStat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Password successfully updated");
        }
        else
            JOptionPane.showMessageDialog(null,"Authentication failure!\nOld password doesn't match");
}
    catch(Exception e )
    {
        System.out.println("Exeution failed at line :-" + e);
    }
    finally{
        try{connection.close();} catch(Exception e) {}            
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_changePassActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void display()   //to display quizes already present in database
    {
        Connection connection =null;
        try{
            list.setModel(mod);
            String subject="";
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/softablitz";
            connection= DriverManager.getConnection(url, "root", "");
            Statement st=connection.createStatement();
            String query1 = "Select DISTINCT(subject) from subjects order by subject";
            PreparedStatement preStat = connection.prepareStatement(query1);
            ResultSet result = preStat.executeQuery();
            while(result.next()) {
                subject=result.getString("subject");
                mod.addElement(subject);
            }
        
}
    catch(Exception e )
    {
        System.out.println("Exeution failed at line :-" + e);
    }
    finally{
        try{connection.close();} catch(Exception e) {}            
    }        
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addSubject;
    public static javax.swing.JButton changePass;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList list;
    private javax.swing.JButton proceed;
    // End of variables declaration//GEN-END:variables
}
